name: Deploy to GitHub Pages

on:
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Pages
              uses: actions/configure-pages@v5
            - name: Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: '.'
        
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        permissions:
            id-token: write
            pages: write
        
        steps:
            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v4